football_terms = {
    "Offside": "Occurs when an attacking player is nearer to the opponent's goal line than both the ball and second-last defender at the moment the ball is passed to them.",
    "Penalty": "A direct free kick awarded to the attacking team when a defender commits a foul inside their penalty area.",
    "Corner Kick": "Awarded to the attacking team when the ball crosses the goal line after last touching a defender, without a goal being scored.",
    "Free Kick": "A kick given after a foul; direct free kicks allow scoring directly, indirect free kicks require a second touch before a goal.",
    "Throw-In": "A method of restarting play when the ball crosses a sideline; the opposing team throws the ball back into play.",
    "Goal Kick": "Awarded to the defending team when the attacking team sends the ball over the goal line without scoring.",
    "Offside Trap": "A defensive tactic where defenders move forward to catch attackers offside.",
    "Yellow Card": "A caution shown by the referee as a warning for unsporting behavior or minor fouls.",
    "Red Card": "Shown by the referee to send off a player for serious fouls, resulting in removal from the game.",
    "Foul": "An unfair or illegal a,ction against an opponent, such as tripping or holding.",
    "Handball": "An offense where a player intentionally touches the ball with their hand or arm.",
    "Goal Line": "The line a ball must fully cross between the goalposts to count as a goal.",
    "Penalty Area": "Also called the 18-yard box; area where goalkeepers can handle the ball and penalty fouls are punished.",
    "Goalkeeper": "The player allowed to handle the ball within the penalty area to protect the goal.",
    "Defender": "A player primarily tasked with stopping the opposing team's attack.",
    "Midfielder": "A player who links defense and attack, often covering large areas of the pitch.",
    "Forward": "An attacking player focused on scoring goals.",
    "Kick-off": "The way to start or restart play from the center of the field.",
    "Extra Time": "Additional playing time added when a match requires a winner after a draw.",
    "Injury Time": "Additional time added for stoppages during each half.",
    "Substitution": "Replacing a player on the field with another from the bench.",
    "Dribble": "Controlling and moving the ball using small, repeated touches.",
    "Tackle": "An attempt to take the ball away from an opponent.",
    "Advantage Rule": "Allowing play to continue after a foul if it benefits the fouled team.",
    "Wall": "A group of defending players lined up to block a free kick.",
    "Hat-Trick": "When a player scores three goals in a single game.",
    "Set Piece": "A planned play such as a free kick or corner after a stoppage.",
    "Man Marking": "Defenders assigned to closely guard individual opponents.",
    "Zonal Marking": "Defenders cover assigned areas rather than specific players.",
    "Bicycle Kick": "An acrobatic kicking move where the player kicks backwards over their own head.",
    "Chip Shot": "A shot that lofts the ball over the goalkeeper.",
    "Cross": "A pass from wide areas into the penalty box to create scoring chances.",
    "Through Ball": "A forward pass played between defenders into space for a teammate.",
    "One-Two": "A quick two-player passing move to bypass defenders.",
    "Direct Free Kick": "A free kick from which a goal can be scored directly.",
    "Indirect Free Kick": "A free kick where the ball must be touched by another player before scoring."
}

basketball_terms = {
    "Three-Second Rule": "A rule that prohibits offensive players from staying in the key (painted area) for more than three consecutive seconds.",
    "Free Throw": "A shot awarded after a foul, taken unopposed from the free-throw line worth one point.",
    "Traveling": "A violation when a player moves illegally without dribbling the ball.",
    "Shot Clock": "A timer limiting the offensive team to a set number of seconds (usually 24) to attempt a shot.",
    "Rebound": "Gaining possession of the ball after a missed shot.",
    "Assist": "A pass that directly leads to a teammate scoring a basket.",
    "Block": "Deflecting or stopping an opponent's shot attempt.",
    "Steal": "Taking the ball away from the opponent through defensive play.",
    "Technical Foul": "Penalty for unsportsmanlike behavior or rule violations not involving physical fouls.",
    "Double-Double": "Achieving double digits in two statistical categories in one game, e.g., points and rebounds.",
    "Alley-Oop": "A play where one player throws the ball near the basket to a teammate who catches and scores in one motion.",
    "Pick and Roll": "An offensive play where a player sets a screen (pick) and then moves toward the basket to receive a pass.",
    "Zone Defense": "A defensive strategy where players cover areas of the court rather than individual opponents.",
    "Man-to-Man Defense": "A defensive strategy where each player guards a specific opponent.",
    "Fast Break": "A quick offensive transition aiming to score before the defense sets up."
}

f1_terms = {
    "Pole Position": "The first starting spot on the grid earned by the fastest qualifier.",
    "Apex": "The innermost part of a corner drivers aim to clip for optimal speed.",
    "DRS": "Drag Reduction System—a device that opens a flap on the rear wing to reduce drag and increase speed.",
    "Safety Car": "Car deployed to control race pace and ensure safety after incidents.",
    "Pit Stop": "A short stop during the race for tire changes and repairs.",
    "Grid Penalty": "A penalty moving a driver back several positions on the starting grid.",
    "Oversteer": "When the rear tires lose grip and the car turns more than intended.",
    "Understeer": "When the front tires lose grip and the car turns less than intended.",
    "DRS Zone": "Parts of the track where the Drag Reduction System can be activated.",
    "Constructor": "The team responsible for building the car and entering the championship.",
    "Downforce": "Aerodynamic force pushing the car down onto the track for better grip.",
    "Telemetry": "Real-time data from the car’s sensors transmitted to the team for analysis.",
    "Qualifier": "The session determining the starting order for the race based on fastest lap times.",
    "Formation Lap": "The lap before the race start where drivers warm up tires and prepare.",
    "Chicane": "A tight series of corners designed to slow cars down."
}